(part "5502-15SA-01-F1"
    (packageRef "550215SA01F1")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
        (port "7" (symbPinId 7) (portName "7") (portType INOUT))
        (port "8" (symbPinId 8) (portName "8") (portType INOUT))
        (port "9" (symbPinId 9) (portName "9") (portType INOUT))
        (port "10" (symbPinId 10) (portName "10") (portType INOUT))
        (port "11" (symbPinId 11) (portName "11") (portType INOUT))
        (port "12" (symbPinId 12) (portName "12") (portType INOUT))
        (port "13" (symbPinId 13) (portName "13") (portType INOUT))
        (port "14" (symbPinId 14) (portName "14") (portType INOUT))
        (port "15" (symbPinId 15) (portName "15") (portType INOUT))
        (port "MH1" (symbPinId 16) (portName "MH1") (portType INOUT))
        (port "MH2" (symbPinId 17) (portName "MH2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "Multicomp Pro")
    (property "Manufacturer_Part_Number" "5502-15SA-01-F1")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "D Sub Connector, Standard, Receptacle, 5502, 15 Contacts, DA, Solder")
    (property "Datasheet_Link" "https://4donline.ihs.com/images/VipMasterIC/IC/SCMP/SCMP-S-A0011490128/SCMP-S-A0011490128-1.pdf?hkey=6D3A4C79FDBF58556ACFDE234799DDF0")
    (property "symbolName1" "5502-15SA-01-F1")
)
